#!/usr/bin/env python3
"""
yaml2gn.py — Converte YAML config para args.gn

Uso:
  python3 yaml2gn.py configs/v8-chrome.yaml fast > out/d8-fast/args.gn
  python3 yaml2gn.py configs/v8-chrome.yaml tsan > out/d8-tsan/args.gn
  python3 yaml2gn.py configs/v8-chrome.yaml fast --validate  # so valida, nao gera

Validacoes:
  - family: sanitizer OBRIGA v8_enable_memory_corruption_api: false
  - family: sandbox OBRIGA is_asan: false (ou ausente)
  - Se violar: GRITA e exit 1

Output: conteudo de args.gn no stdout
"""
import sys
import yaml
import json
from pathlib import Path


def validate_config(config_name: str, config: dict) -> list[str]:
    """Valida integridade do config. Retorna lista de erros."""
    errors = []
    family = config.get("family", "unknown")
    gn = config.get("gn_args", {})

    if family == "sanitizer":
        if gn.get("v8_enable_memory_corruption_api") is True:
            errors.append(
                f"CONFIG {config_name}: family=sanitizer mas v8_enable_memory_corruption_api=true! "
                f"ASAN sequestra SIGSEGV, crash filter nao funciona. "
                f"V8 BUILD.gn tem assert bloqueando is_asan + memory_corruption_api."
            )
        if gn.get("is_asan") is False and gn.get("is_tsan") is not True and gn.get("is_ubsan") is not True:
            errors.append(
                f"CONFIG {config_name}: family=sanitizer mas nenhum sanitizer ativo! "
                f"Precisa de is_asan, is_tsan, ou is_ubsan = true."
            )

    elif family == "sandbox":
        if gn.get("v8_enable_memory_corruption_api") is False:
            errors.append(
                f"CONFIG {config_name}: family=sandbox mas v8_enable_memory_corruption_api=false! "
                f"Sem a API, Sandbox.MemoryView nao sera exposto."
            )
        if gn.get("is_asan") is True:
            errors.append(
                f"CONFIG {config_name}: family=sandbox mas is_asan=true! "
                f"ASAN eh incompativel com sandbox crash filter."
            )
        if gn.get("is_tsan") is True:
            errors.append(
                f"CONFIG {config_name}: family=sandbox mas is_tsan=true! "
                f"Sanitizers devem usar family=sanitizer."
            )

    else:
        errors.append(f"CONFIG {config_name}: family desconhecida '{family}'. Use: sandbox | sanitizer")

    return errors


def gn_value(v) -> str:
    """Converte valor Python para formato GN."""
    if isinstance(v, bool):
        return "true" if v else "false"
    elif isinstance(v, int):
        return str(v)
    elif isinstance(v, str):
        return f'"{v}"'
    else:
        return str(v)


def generate_args_gn(yaml_path: str, config_name: str, validate_only: bool = False) -> str:
    """Gera conteudo de args.gn a partir do YAML."""
    with open(yaml_path) as f:
        cfg = yaml.safe_load(f)

    if config_name not in cfg.get("configs", {}):
        available = ", ".join(cfg.get("configs", {}).keys())
        print(f"ERRO: Config '{config_name}' nao existe no YAML!", file=sys.stderr)
        print(f"Configs disponiveis: {available}", file=sys.stderr)
        sys.exit(1)

    config = cfg["configs"][config_name]
    base = cfg.get("base", {})
    gn_args = config.get("gn_args", {})

    # Validar
    errors = validate_config(config_name, config)
    if errors:
        for e in errors:
            print(f"ERRO DE VALIDACAO: {e}", file=sys.stderr)
        sys.exit(1)

    if validate_only:
        print(f"Config '{config_name}' validado OK (family={config['family']})")
        return ""

    # Merge: base + config (config sobrescreve)
    merged = {**base, **gn_args}

    # Gerar args.gn
    lines = []
    lines.append(f"# Auto-generated from {Path(yaml_path).name}, config: {config_name}")
    lines.append(f"# Family: {config['family']}")
    lines.append(f"# Description: {config.get('description', 'N/A')}")
    lines.append(f"# Generated by yaml2gn.py — NAO EDITAR MANUALMENTE")
    lines.append("")

    for k, v in merged.items():
        lines.append(f"{k} = {gn_value(v)}")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 3:
        print("Uso: yaml2gn.py <yaml_path> <config_name> [--validate]", file=sys.stderr)
        print("     yaml2gn.py configs/v8-chrome.yaml fast", file=sys.stderr)
        print("     yaml2gn.py configs/v8-chrome.yaml tsan --validate", file=sys.stderr)
        sys.exit(1)

    yaml_path = sys.argv[1]
    config_name = sys.argv[2]
    validate_only = "--validate" in sys.argv

    if not Path(yaml_path).exists():
        print(f"ERRO: YAML nao encontrado: {yaml_path}", file=sys.stderr)
        sys.exit(1)

    result = generate_args_gn(yaml_path, config_name, validate_only)
    if result:
        print(result)


if __name__ == "__main__":
    main()
